heat_template_version: 2014-10-16

parameters:
  DockerAgentImage:
    type: string
    default: dprince/heat-docker-agents-centos

resources:

  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: install_docker_agents}

  install_docker_agents:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          params:
            $agent_image: {get_param: DockerAgentImage}
          template: {get_file: ./start_docker_agents.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
